### PR TITLE
#1 Update HelloWorldTest.kt

### PR DESCRIPTION
**Pull request by chris0197**
change the class name to the same as the file

### CODE REVIEW

**Comment by nipafx** [comment]
I don't get why this is necessary. What problem or issue does it address?

**Comment by chris0197** [comment]
#18 @nicolaiparlog  say that the class should have the same name as the file

**Comment by nipafx** [comment]
Oh, ok. Yes, that's preferred. :+1:

**Comment by chris0197** [comment]
@nicolaiparlog 
now we can merge it ??

**Comment by nipafx** [comment]
Yes, hence the :+1:

**Pull request merged**
